# Generated by Django 5.1.1 on 2024-11-26 22:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID de Empleado')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Contratación')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Activo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'employees',
                'ordering': ['-hire_date'],
            },
        ),
    ]
