# Generated by Django 5.1.1 on 2024-10-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_efectiva', models.DateField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
