# Generated by Django 5.1.2 on 2024-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
    ]
