# Generated by Django 5.1.1 on 2024-09-09 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'is_cliente': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='employees.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='mueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mueble'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_pedido', to='orders.pedido'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='puerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.puerta'),
        ),
        migrations.AddField(
            model_name='productopedido',
            name='ventana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ventana'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='muebles',
            field=models.ManyToManyField(related_name='pedidos_muebles', through='orders.ProductoPedido', to='products.mueble'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='puertas',
            field=models.ManyToManyField(related_name='pedidos_puertas', through='orders.ProductoPedido', to='products.puerta'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ventanas',
            field=models.ManyToManyField(related_name='pedidos_ventanas', through='orders.ProductoPedido', to='products.ventana'),
        ),
    ]
