# Generated by Django 5.1.1 on 2024-10-02 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('numero_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_madera', models.CharField(max_length=50)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barnizado', models.BooleanField(default=False)),
                ('productor', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=7)),
                ('nombre_pieza', models.CharField(max_length=100)),
                ('parte_juego', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('numero_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_madera', models.CharField(max_length=50)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barnizado', models.BooleanField(default=False)),
                ('productor', models.CharField(max_length=100)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_hojas', models.IntegerField()),
                ('exterior', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ventana',
            fields=[
                ('numero_producto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_madera', models.CharField(max_length=50)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barnizado', models.BooleanField(default=False)),
                ('productor', models.CharField(max_length=100)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_hojas', models.IntegerField()),
                ('exterior', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('mueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mueble')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_pedido', to='orders.pedido')),
                ('puerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.puerta')),
                ('ventana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ventana')),
            ],
        ),
    ]
